def base_file_hindi(self):
    base_message = ""
    base_message += "<!-- CREATED BY (BHAML HINDI)-BHARAT MARKUP LANGUAGE CODE EDITOR v1.0 -->\n"
    base_message += "<!-------------------- BHAML AUTHOR: NIKHIL MALHOTRA--------------------->\n"
    base_message += "<भामल>"
    base_message += "\n\n\t<हैड>"
    base_message += "\n\t\t<शीर्षक>भारत कोड</शीर्षक>"
    base_message += "\n\t<लिपि language=""Javascript"">"
    base_message += "\n\n\t\tfunction message()"
    base_message += "\n\n\t\t{"
    base_message += "\n\n\t\t\talert('hello world!');"
    base_message += "\n\n\t\t}"
    base_message += "\n\n\t</लिपि>"
    base_message += "\n\t</हैड>"
    base_message += "\n\n\t<बौडी>"
    base_message += "\n\t\t<पैरा>Hello there! mera naam Nikhil hai!</पैरा>"
    base_message += "\n\t\t<ए href=""http://www.google.com"">Google</ए>"
    base_message += "\n\t\t<इनपुट type=button value='क्लिक' onClick='message();'></इनपुट>"
    base_message += "\n\t</बौडी>"
    base_message += "\n\n</भामल>"

    return base_message 

def base_file_telugu(self):
    base_message = ""
    base_message += "<!-- CREATED BY (BHAML TELUGU)-BHARAT MARKUP LANGUAGE CODE EDITOR v1.0 -->\n"
    base_message += "<!-------------------- BHAML AUTHOR: NIKHIL MALHOTRA--------------------->\n"
    base_message += "<బిమల్>"
    base_message += "\n\n\t<హెడ్>"
    base_message += "\n\t\t<శీర్షిక>भारत कोड</శీర్షిక>"
    base_message += "\n\t<స్క్రిప్ట్ language=""Javascript"">"
    base_message += "\n\n\t\tfunction message()"
    base_message += "\n\n\t\t{"
    base_message += "\n\n\t\t\talert('hello world!');"
    base_message += "\n\n\t\t}"
    base_message += "\n\n\t</స్క్రిప్ట్>"
    base_message += "\n\t</హెడ్>"
    base_message += "\n\n\t<శరీరం>"
    base_message += "\n\t\t<పేరా>Hello there! mera naam Nikhil hai!</పేరా>"
    base_message += "\n\t\t<ఏ href=""http://www.google.com"">Google</ఏ>"
    base_message += "\n\t\t<ఇన్పుట్ type=button value='क्लिक' onClick='message();'></ఇన్పుట్>"
    base_message += "\n\t</శరీరం>"
    base_message += "\n\n</బిమల్>"

    return base_message 

def base_file_tamil(self):
    base_message = ""
    base_message += "<!-- CREATED BY (BHAML TAMIL)-BHARAT MARKUP LANGUAGE CODE EDITOR v1.0 -->\n"
    base_message += "<!-------------------- BHAML AUTHOR: NIKHIL MALHOTRA--------------------->\n"
    base_message += "<ଭମଳ>"
    base_message += "\n\n\t<ମୁଣ୍ଡ>"
    base_message += "\n\t\t<ଆଖ୍ୟା>भारत कोड</ଆଖ୍ୟା>"
    base_message += "\n\t<ଲିପି ଭାଷା=""Javascript"">"
    base_message += "\n\n\t\tfunction message()"
    base_message += "\n\n\t\t{"
    base_message += "\n\n\t\t\talert('hello world!');"
    base_message += "\n\n\t\t}"
    base_message += "\n\n\t</ଲିପି>"
    base_message += "\n\t</ମୁଣ୍ଡ>"
    base_message += "\n\n\t<ଶରୀର>"
    base_message += "\n\t\t<ଅନୁଚ୍ଛେଦ>Hello there! mera naam Nikhil hai!</ଅନୁଚ୍ଛେଦ>"
    base_message += "\n\t\t<ଏ ସନ୍ଦର୍ଭ=""http://www.google.com"">Google</ଏ>"
    base_message += "\n\t\t<ଇନପୁଟ୍ ପ୍ରକାର=ବଟନ୍ value='क्लिक' onClick='message();'></ଇନପୁଟ୍>"
    base_message += "\n\t</ଶରୀର>"
    base_message += "\n\n</ଭମଳ>"

    return base_message 

def base_file_punjabi(self):
    base_message = ""
    base_message += "<!-- CREATED BY (BHAML PUNJABI)-BHARAT MARKUP LANGUAGE CODE EDITOR v1.0 -->\n"
    base_message += "<!-------------------- BHAML AUTHOR: NIKHIL MALHOTRA--------------------->\n"
    base_message += "<ਭਮਲ>"
    base_message += "\n\n\t<ਸਿਰ>"
    base_message += "\n\t\t<ਪਹਿਲਾਂ>भारत कोड</ਪਹਿਲਾਂ>"
    base_message += "\n\t<ਸਕ੍ਰਿਪਟ language=""Javascript"">"
    base_message += "\n\n\t\tfunction message()"
    base_message += "\n\n\t\t{"
    base_message += "\n\n\t\t\talert('hello world!');"
    base_message += "\n\n\t\t}"
    base_message += "\n\n\t</ਸਕ੍ਰਿਪਟ>"
    base_message += "\n\t</ਸਿਰ>"
    base_message += "\n\n\t<ਸਰੀਰ>"
    base_message += "\n\t\t<ਪੈਰਾ>Hello there! mera naam Nikhil hai!</ਪੈਰਾ>"
    base_message += "\n\t\t<ਏ href=""http://www.google.com"">Google</ਏ>"
    base_message += "\n\t\t<ਇੰਪੁੱਟ type=button value='क्लिक' onClick='message();'></ਇੰਪੁੱਟ>"
    base_message += "\n\t</ਸਰੀਰ>"
    base_message += "\n\n</ਭਮਲ>"

    return base_message 

def base_file_odiya(self):
    base_message = ""
    base_message += "<!-- CREATED BY (BHAML ODIYA)-BHARAT MARKUP LANGUAGE CODE EDITOR v1.0 -->\n"
    base_message += "<!-------------------- BHAML AUTHOR: NIKHIL MALHOTRA--------------------->\n"
    base_message += "<ଭମଳ>"
    base_message += "\n\n\t<ଶୀର୍ଷ>"
    base_message += "\n\t\t<ଆଖ୍ୟା>भारत कोड</ଆଖ୍ୟା>"
    base_message += "\n\t<ଲିପି language=""Javascript"">"
    base_message += "\n\n\t\tfunction message()"
    base_message += "\n\n\t\t{"
    base_message += "\n\n\t\t\talert('hello world!');"
    base_message += "\n\n\t\t}"
    base_message += "\n\n\t</ଲିପି>"
    base_message += "\n\t</ଶୀର୍ଷ>"
    base_message += "\n\n\t<ଶରୀର>"
    base_message += "\n\t\t<ଅନୁଚ୍ଛେଦ>Hello there! mera naam Nikhil hai!</ଅନୁଚ୍ଛେଦ>"
    base_message += "\n\t\t<ଏ href=""http://www.google.com"">Google</ଏ>"
    base_message += "\n\t\t<ଇନପୁଟ୍ type=button value='क्लिक' onClick='message();'></ଇନପୁଟ୍>"
    base_message += "\n\t</ଶରୀର>"
    base_message += "\n\n</ଭମଳ>"

    return base_message 

def base_file_marathi(self):
    base_message = ""
    base_message += "<!-- CREATED BY (BHAML MARATHI)-BHARAT MARKUP LANGUAGE CODE EDITOR v1.0 -->\n"
    base_message += "<!-------------------- BHAML AUTHOR: NIKHIL MALHOTRA--------------------->\n"
    base_message += "<भामल>"
    base_message += "\n\n\t<हेड​>"
    base_message += "\n\t\t<पदवी>भारत कोड</पदवी>"
    base_message += "\n\t<लिपी language=""Javascript"">"
    base_message += "\n\n\t\tfunction message()"
    base_message += "\n\n\t\t{"
    base_message += "\n\n\t\t\talert('hello world!');"
    base_message += "\n\n\t\t}"
    base_message += "\n\n\t</लिपी>"
    base_message += "\n\t</हेड​>"
    base_message += "\n\n\t<बौडी>"
    base_message += "\n\t\t<परिच्छेद>Hello there! mera naam Nikhil hai!</परिच्छेद>"
    base_message += "\n\t\t<ए href=""http://www.google.com"">Google</ए>"
    base_message += "\n\t\t<इनपुट type=button value='क्लिक' onClick='message();'></इनपुट>"
    base_message += "\n\t</बौडी>"
    base_message += "\n\n</भामल>"

    return base_message

def base_file_maori(self):
    base_message = ""
    base_message += "<!-- CREATED BY (BHAML MAORI)-BHARAT MARKUP LANGUAGE CODE EDITOR v1.0 -->\n"
    base_message += "<!-------------------- BHAML AUTHOR: NIKHIL MALHOTRA--------------------->\n"
    base_message += "<BHAML>"
    base_message += "\n\n\t<upoko>"
    base_message += "\n\t\t<taitara>BHAML Code</taitara>"
    base_message += "\n\t<hōtuhi language=""Javascript"">"
    base_message += "\n\n\t\tfunction message()"
    base_message += "\n\n\t\t{"
    base_message += "\n\n\t\t\talert('hello world!');"
    base_message += "\n\n\t\t}"
    base_message += "\n\n\t</hōtuhi>"
    base_message += "\n\t</upoko>"
    base_message += "\n\n\t<tinana>"
    base_message += "\n\t\t<kōwae>Kia ora! Ko Saket toku ingoa</kōwae>"
    base_message += "\n\t\t<a href=""http://www.google.com"">Google</a>"
    base_message += "\n\t\t<tāuru type=button value='paatohia' onClick='message();'></tāuru>"
    base_message += "\n\t</tinana>"
    base_message += "\n\n</BHAML>"

    return base_message 

def base_file_malayalam(self):
    base_message = ""
    base_message += "<!-- CREATED BY (BHAML MALAYALAM)-BHARAT MARKUP LANGUAGE CODE EDITOR v1.0 -->\n"
    base_message += "<!-------------------- BHAML AUTHOR: NIKHIL MALHOTRA--------------------->\n"
    base_message += "<ഹ്റമാൽ>"
    base_message += "\n\n\t<ഹെഡ്>"
    base_message += "\n\t\t<ടൈറ്റിൽ>भारत कोड</ടൈറ്റിൽ>"
    base_message += "\n\t<സ്കിര്പട് language=""Javascript"">"
    base_message += "\n\n\t\tfunction message()"
    base_message += "\n\n\t\t{"
    base_message += "\n\n\t\t\talert('hello world!');"
    base_message += "\n\n\t\t}"
    base_message += "\n\n\t</സ്കിര്പട്>"
    base_message += "\n\t</ഹെഡ്>"
    base_message += "\n\n\t<ബോഡി>"
    base_message += "\n\t\t<പി>Hello there! mera naam Nikhil hai!</പി>"
    base_message += "\n\t\t<അ href=""http://www.google.com"">Google</അ>"
    base_message += "\n\t\t<ഇന്പുട് type=button value='क्लिक' onClick='message();'></ഇന്പുട്>"
    base_message += "\n\t</ബോഡി>"
    base_message += "\n\n</ഹ്റമാൽ>"

    return base_message 


def base_file_kannada(self):
    base_message = ""
    base_message += "<!-- CREATED BY (BHAML KANNADA)-BHARAT MARKUP LANGUAGE CODE EDITOR v1.0 -->\n"
    base_message += "<!-------------------- BHAML AUTHOR: NIKHIL MALHOTRA--------------------->\n"
    base_message += "<ಬಿಎಂಎಲ್>"
    base_message += "\n\n\t<ಹೆಡ್>"
    base_message += "\n\t\t<ಶೀರ್ಷಿಕೆ>भारत कोड</ಶೀರ್ಷಿಕೆ>"
    base_message += "\n\t<ಸ್ಕ್ರಿಪ್ಟ್ language=""Javascript"">"
    base_message += "\n\n\t\tfunction message()"
    base_message += "\n\n\t\t{"
    base_message += "\n\n\t\t\talert('ಭಾಷೆ भारत!');"
    base_message += "\n\n\t\t}"
    base_message += "\n\n\t</ಸ್ಕ್ರಿಪ್ಟ್>"
    base_message += "\n\t</ಹೆಡ್>"
    base_message += "\n\n\t<ಬಾಡಿ>"
    base_message += "\n\t\t<ಪ್ಯಾರಾ>Hello there! mera naam Nikhil hai!</ಪ್ಯಾರಾ>"
    base_message += "\n\t\t<ಎ href=""http://www.google.com"">Google</ಎ>"
    base_message += "\n\t\t<ಇನ್ಪುಟ್ type=button value='click me' onClick='message();'></ಇನ್ಪುಟ್>"
    base_message += "\n\t</ಬಾಡಿ>"
    base_message += "\n\n</ಬಿಎಂಎಲ್>"

    return base_message 


def base_file_gujarati(self):
    base_message = ""
    base_message += "<!-- CREATED BY (BHAML GUJARATI)-BHARAT MARKUP LANGUAGE CODE EDITOR v1.0 -->\n"
    base_message += "<!-------------------- BHAML AUTHOR: NIKHIL MALHOTRA--------------------->\n"
    base_message += "<ભમલ>"
    base_message += "\n\n\t<હેડ>"
    base_message += "\n\t\t<શીર્ષક>भारत कोड</શીર્ષક>"
    base_message += "\n\t<લિપિ language=""Javascript"">"
    base_message += "\n\n\t\tfunction message()"
    base_message += "\n\n\t\t{"
    base_message += "\n\n\t\t\talert('hello world!');"
    base_message += "\n\n\t\t}"
    base_message += "\n\n\t</લિપિ>"
    base_message += "\n\t</હેડ>"
    base_message += "\n\n\t<બોડી>"
    base_message += "\n\t\t<પી>Hello there! mera naam Nikhil hai!</પી>"
    base_message += "\n\t\t<એ href=""http://www.google.com"">Google</એ>"
    base_message += "\n\t\t<ઇનપુટ type=button value='क्लिक' onClick='message();'></ઇનપુટ>"
    base_message += "\n\t</બોડી>"
    base_message += "\n\n</ભમલ>"

    return base_message 


def base_file_bangla(self):
    base_message = ""
    base_message += "<!-- CREATED BY <ଭମଳ> (BHAML BANGLA)-BHARAT MARKUP LANGUAGE CODE EDITOR v1.0 -->\n"
    base_message += "<!-------------------- BHAML AUTHOR: NIKHIL MALHOTRA--------------------->\n"
    base_message += "<ଭମଳ>"
    base_message += "\n\n\t<ମୁଣ୍ଡ>"
    base_message += "\n\t\t<ଆଖ୍ୟା>भारत कोड</ଆଖ୍ୟା>"
    base_message += "\n\t<ଲିପି ଭାଷା=""Javascript"">"
    base_message += "\n\n\t\tfunction message()"
    base_message += "\n\n\t\t{"
    base_message += "\n\n\t\t\talert('hello world!');"
    base_message += "\n\n\t\t}"
    base_message += "\n\n\t</ଲିପି>"
    base_message += "\n\t</ମୁଣ୍ଡ>"
    base_message += "\n\n\t<ଶରୀର>"
    base_message += "\n\t\t<ଅନୁଚ୍ଛେଦ>Hello there! mera naam Nikhil hai!</ଅନୁଚ୍ଛେଦ>"
    base_message += "\n\t\t<ଏ ସନ୍ଦର୍ଭ=""http://www.google.com"">Google</ଏ>"
    base_message += "\n\t\t<ଇନପୁଟ୍ ପ୍ରକାର=ବଟନ୍ value='क्लिक' onClick='message();'></ଇନପୁଟ୍>"
    base_message += "\n\t</ଶରୀର>"
    base_message += "\n\n</ଭମଳ>"

    return base_message 

def base_file_arabic(self):
    base_message = ""
    base_message += "<!-- CREATED BY (BHAML ARABIC)-BHARAT MARKUP LANGUAGE CODE EDITOR v1.0 -->\n"
    base_message += "<!-------------------- BHAML AUTHOR: NIKHIL MALHOTRA--------------------->\n"
    base_message += "<بحامل>"
    base_message += "\n\n\t<رأس>"
    base_message += "\n\t\t<لقب>كود الهند</لقب>"
    base_message += "\n\t<النصي language=""Javascript"">"
    base_message += "\n\n\t\tfunction message()"
    base_message += "\n\n\t\t{"
    base_message += "\n\n\t\t\talert('hello world!');"
    base_message += "\n\n\t\t}"
    base_message += "\n\n\t</النصي>"
    base_message += "\n\t</رأس>"
    base_message += "\n\n\t<الجسم>"
    base_message += "\n\t\t<فقرة>Hello there! mera naam Nikhil hai!</فقرة>"
    base_message += "\n\t\t<أ href=""http://www.google.com"">Google</أ>"
    base_message += "\n\t\t<إدخال type=button value='كاليك' onClick='message();'></إدخال>"
    base_message += "\n\t</الجسم>"
    base_message += "\n\n</بحامل>"

    return base_message